"""baseline

Revision ID: 39d958420658
Revises: 
Create Date: 2026-09-06 16:42:18.907067

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '39d958420658'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('tier_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('claim_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_claim', 'download_jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_download_jobs_user_id'), 'download_jobs', ['user_id'], unique=False)
    op.create_table('quota_usage',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('bytes_down', sa.BigInteger(), nullable=False),
    sa.Column('bytes_up', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'period_start', 'period_type')
    )
    op.create_table('referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('invitee_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_referrals_invitee')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('download_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['download_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_user', 'download_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_download_history_user_id'), 'download_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_history_user_id'), table_name='download_history')
    op.drop_index('idx_history_user', table_name='download_history')
    op.drop_table('download_history')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('quota_usage')
    op.drop_index(op.f('ix_download_jobs_user_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_index('idx_jobs_claim', table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
